# =======================================================
# Profil 'dev' (Section 6 - Pour aller plus loin)
# =======================================================

# Niveau de log plus verbeux en developpement
logging.level.tn.esprit.autoloc=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Affichage et formatage des requetes SQL generees
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
